import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
    version: 1,
    tables: [
        tableSchema({
            name: 'profiles',
            columns: [
                { name: 'username', type: 'string', isOptional: true },
                { name: 'class', type: 'string' },
                { name: 'level', type: 'number' },
                { name: 'current_xp', type: 'number' },
                { name: 'max_xp', type: 'number' },
                { name: 'hp_current', type: 'number' },
                { name: 'hp_max', type: 'number' },
                { name: 'gold', type: 'number' },
                { name: 'current_status', type: 'string' },
                { name: 'avatar_url', type: 'string', isOptional: true },
                { name: 'shame_count', type: 'number' },
                { name: 'total_study_minutes', type: 'number' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'user_stats',
            columns: [
                { name: 'mastery_xp', type: 'number' },
                { name: 'mastery_level', type: 'number' },
                { name: 'wisdom_xp', type: 'number' },
                { name: 'wisdom_level', type: 'number' },
                { name: 'vigor_xp', type: 'number' },
                { name: 'vigor_level', type: 'number' },
                { name: 'discipline_xp', type: 'number' },
                { name: 'discipline_level', type: 'number' },
                { name: 'global_level', type: 'number' },
                { name: 'cronolitos_balance', type: 'number' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'subjects',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'color', type: 'string' },
                { name: 'course', type: 'string', isOptional: true },
                { name: 'is_completed', type: 'boolean' },
                { name: 'total_minutes_studied', type: 'number' },
                { name: 'final_grade', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'books',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'title', type: 'string' },
                { name: 'author', type: 'string' },
                { name: 'total_pages', type: 'number' },
                { name: 'current_page', type: 'number' },
                { name: 'cover_color', type: 'string' },
                { name: 'saga', type: 'string', isOptional: true },
                { name: 'saga_index', type: 'number' },
                { name: 'is_finished', type: 'boolean' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'study_sessions',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'subject_id', type: 'string', isOptional: true, isIndexed: true },
                { name: 'book_id', type: 'string', isOptional: true, isIndexed: true },
                { name: 'activity_id', type: 'string', isOptional: true, isIndexed: true },
                { name: 'start_time', type: 'string' },
                { name: 'end_time', type: 'string' },
                { name: 'duration_minutes', type: 'number' },
                { name: 'status', type: 'string' },
                { name: 'difficulty', type: 'string' },
                { name: 'mode', type: 'string' },
                { name: 'notes', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'routines',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'description', type: 'string', isOptional: true },
                { name: 'category', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'routine_exercises',
            columns: [
                { name: 'routine_id', type: 'string', isIndexed: true },
                { name: 'exercise_id', type: 'string', isIndexed: true },
                { name: 'order_index', type: 'number' },
                { name: 'target_sets', type: 'number' },
                { name: 'target_reps', type: 'number' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'exercises',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'name_es', type: 'string', isOptional: true },
                { name: 'category', type: 'string' },
                { name: 'equipment', type: 'string' },
                { name: 'intensity_factor', type: 'number' },
                { name: 'bodyweight_factor', type: 'number' },
                { name: 'is_popular', type: 'boolean' },
                { name: 'is_favorite', type: 'boolean' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'workout_sessions',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'routine_id', type: 'string', isOptional: true, isIndexed: true },
                { name: 'started_at', type: 'number' },
                { name: 'ended_at', type: 'number', isOptional: true },
                { name: 'bodyweight', type: 'number', isOptional: true },
                { name: 'note', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'workout_sets',
            columns: [
                { name: 'session_id', type: 'string', isIndexed: true },
                { name: 'exercise_id', type: 'string', isIndexed: true },
                { name: 'set_number', type: 'number' },
                { name: 'weight_kg', type: 'number' },
                { name: 'reps', type: 'number' },
                { name: 'rpe', type: 'number', isOptional: true },
                { name: 'type', type: 'string' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'theatre_activities',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'total_minutes', type: 'number' },
                { name: 'days_count', type: 'number' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'theatre_movies',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'title', type: 'string' },
                { name: 'director', type: 'string', isOptional: true },
                { name: 'saga', type: 'string', isOptional: true },
                { name: 'rating', type: 'number' },
                { name: 'comment', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'theatre_series',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'title', type: 'string' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'theatre_seasons',
            columns: [
                { name: 'series_id', type: 'string', isIndexed: true },
                { name: 'season_number', type: 'number' },
                { name: 'episodes_count', type: 'number' },
                { name: 'rating', type: 'number' },
                { name: 'comment', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'temple_thoughts',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'content', type: 'string' },
                { name: 'type', type: 'string' },
                { name: 'is_resolved', type: 'boolean' },
                { name: 'is_encrypted', type: 'boolean' },
                { name: 'date', type: 'string' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'temple_sleep',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'hours', type: 'number' },
                { name: 'quality', type: 'string', isOptional: true },
                { name: 'date', type: 'string' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'tavern_water',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'amount', type: 'number' },
                { name: 'date', type: 'string' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'mage_themes',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'symbol', type: 'string' },
                { name: 'color', type: 'string' },
                { name: 'pending_aura', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'mage_projects',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'theme_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'target_aura', type: 'number' },
                { name: 'current_aura', type: 'number' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'royal_decrees',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'title', type: 'string' },
                { name: 'type', type: 'string' },
                { name: 'status', type: 'string' },
                { name: 'target_quantity', type: 'number' },
                { name: 'current_quantity', type: 'number' },
                { name: 'due_date', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'daily_rituals',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'icon', type: 'string' },
                { name: 'schedule_type', type: 'string' },
                { name: 'weekly_target', type: 'number' },
                { name: 'activity_type', type: 'string', isOptional: true },
                { name: 'activity_tag', type: 'string', isOptional: true },
                { name: 'target_value', type: 'number' },
                { name: 'unit', type: 'string' },
                { name: 'current_streak', type: 'number' },
                { name: 'is_active', type: 'boolean' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'ritual_logs',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'ritual_id', type: 'string', isIndexed: true },
                { name: 'date', type: 'string' },
                { name: 'current_value', type: 'number' },
                { name: 'target_value', type: 'number' },
                { name: 'completed', type: 'boolean' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'custom_colors',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'hex_code', type: 'string' },
                { name: 'name', type: 'string', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'app_aura_mappings',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'process_name', type: 'string' },
                { name: 'theme_id', type: 'string' },
                { name: 'created_at', type: 'number' },
            ],
        }),
    ],
});
